[package]
name = "examples"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "in_memory"
path = "src/bin/in_memory.rs"

[[bin]]
name = "reconcile"
path = "src/bin/reconcile.rs"

[[bin]]
name = "topic_sync"
path = "src/bin/topic_sync.rs"

[dependencies]
psi = { path = "../psi" }
reconciliation = { path = "../reconciliation" }
topic-sync = { path = "../topic-sync" }
rand.workspace = true
